### ISSUE TITLE
Switched description for push/pop

### ISSUE THREAD

**Issue by andrepcg** [asmcup/runtime#1]
Did you mean
**PUSH:** _saves_ data onto the stack
**POP:** _loads_ data from the stack

instead of 
**PUSH:** _loads_ data onto the stack
**POP:** _saves_ data from the stack

?

**Comment by krisives** [comment]
The terminology of "load" and "save" (or "store") is adopted from Java bytecode:

https://en.wikipedia.org/wiki/Java_bytecode_instruction_listings

That instruction set is much larger and more complex, but within it they use opcodes like `aload_0` with descriptions like "load a reference onto the stack from local variable 0". I am trying to stay consistent with that.

Pushing or popping from the stack ultimately is a transfer of memory from `ram[x]` to `ram[y]` so the terminology of what is doing the "loading" or "saving" could be subjective. Let's take the simplest program:

```
push8 #$77
pop8 $20
```

Rewritten as Java code it would look like this:

```
ram[0xFF] = 0x77;
ram[0x20] = ram[0xFF];
```
