### ISSUE TITLE
Ray tracing values

### ISSUE THREAD

**Issue by MLanghof** [asmcup/runtime#11]
Currently the ray tracing performs 10 steps and simply outputs the 16*step number where the first collision happens. Not only does this comfortably fit into a byte instead of a float, it's also quite inaccurate due to the large step sizes (not sure if intended).

Should it eventually have more steps and output a somewhat precise distance? Regardless, I'd suggest making it return a byte unless there's a reason why sub-unit precision (or values > 255) are needed.

**Comment by krisives** [comment]
This will change to a byte soon. I'm open to ideas on how to pick good iteration values for the ray test.

**Comment by MLanghof** [comment]
Well, 16 is half the tile size, so it will skip over corners. Given that the robot is (a lot) wider than the beam, it would already get stuck on some corners even if the ray tracing was perfect, so I'd do something like 4 or 8 as step size to not exaggerate it.

**Comment by MLanghof** [comment]
Should be fixed by a30aa70.
