### ISSUE TITLE
Genetics: ProgramSize has no effect

### ISSUE THREAD

**Issue by MLanghof** [asmcup/runtime#110]
Currently, the GA starts with programs of size 256 and only creates new programs by crossing existing ones (meaning the size is retained). Since the GA is initialized at program start, the spinner for program size has zero effect.

What would the intended behavior be when changing program size? All DNA is reset (re-randomized)? Existing DNA is shortened if the program size is reduced, and filled up (with zeroes? Or random bytes?) when it's increased?

**Comment by krisives** [comment]
The current use of the programSize would be to allow programs to generate "memory" by running the program at say 256 size, then changing the size to 32 to only change the starting portion of the program size. I agree it's not implemented in a way that allows for fine-grained usage, but to say it has zero effect is a bit extreme.

I also use it when generating new programs by starting the program size to be low and increasing it over time. It really depends on the view of "junk DNA" and I'm not sure about that. Feedback is always wanted.

**Comment by MLanghof** [comment]
Oh, I see. I had the assumption that the non-DNA part of programs was supposed to be padded with zeros, hence the "zero effect" part.

The "junk DNA" leftovers (i.e. ROM past `programSize`) that aren't ever changed do have a significant impact on the bot behavior though (unless you limit PC to remain within programSize), so I'm a bit surprised this is intended (?) behavior.

**Comment by krisives** [comment]
I had some changes that enforced PC being within programSize as well as PC never being within the "stack area" if enforced.

The main goal here is to allow programs to be "raised" in different stages starting with a small program size and increasing it as needed. Without this a program is left mutating many bytes which don't affect the basic needs of an early bot that still has no basic driving or main loop which can be accomplished in much less than 256 bytes.

**Comment by MLanghof** [comment]
Closing this. It was first and foremost a misunderstanding, if there's any actual changes still needed then a separate ticket should be opened.
