### ISSUE TITLE
Variable beam angles

### ISSUE THREAD

**Issue by MLanghof** [asmcup/runtime#111]
@krisives previously suggested to make the beam angles (sensor and laser, relative to bot facing) changeable via an IO command.

What do you guys think on the matter?

**Comment by krisives** [comment]
My suggestion is we either stuff it into `IO_SENSOR_CONFIG` or add `IO_SENSOR_ROTATE` to set the rotation angle of the beam. By default it would be at 0 rotation facing in front of you.

Should we have it set a value based on PI or normalized value from `0.0` - `1.0` ?

**Comment by RayWillett** [comment]
Would we want the beam to be able to move beyond 90 degrees to either side? I think that should bear some weight in the decision.

**Comment by MLanghof** [comment]
Implemented in #126.
