### ISSUE TITLE
testAccelerometer failed non-deterministcally

### ISSUE THREAD

**Issue by krisives** [asmcup/runtime#114]
See https://github.com/asmcup/runtime/pull/113#issuecomment-257088864

**Comment by SiebelsTim** [comment]
Damn. I will look into it. But will most likely not get to it before Monday. Remove it if you want, I'll take care of it

**Comment by MLanghof** [comment]
Well the reason is pretty clear: The testing code is confused about the difference between tile coordinates (rows/cols) and bot coordinates (x/y).

I'll fix it later today.
