### ISSUE TITLE
Robots can spawn stuck

### ISSUE THREAD

**Issue by MLanghof** [asmcup/runtime#13]
There's no check if the terrain is blocked at the (random) starting location.

**Comment by MLanghof** [comment]
On a similar note, nothing prevents obstacles from enclosing the starting location.

**Comment by krisives** [comment]
This is a bug of the Sandbox. A check needs to be added for isSolid before spawning. Outside of sandbox mode robots should never spawn stuck, although they can spawn near hazards etc.

**Comment by SiebelsTim** [comment]
is this fixed by c01d97e8d61a10b085031d93b324f0170c3e66a7?

**Comment by krisives** [comment]
Yes it should be fixed I wanted to get some feedback before I closed it.
