### ISSUE TITLE
Beam/bot interaction

### ISSUE THREAD

**Issue by MLanghof** [asmcup/runtime#132]
Currently, neither laser nor sensor interact with other bots in the world.

I would like to point out that the beam sensor currently has no bits in its field left to indicate the presence of bots. I have opened #133 in relation to this.

**Comment by kirtangajjar** [comment]
Was thinking of this. Would be great if beam sensor could detect gold/battery

**Comment by MLanghof** [comment]
You mean that it should detect gold and battery of other bots? That's borderline impossible, because we can't simply push those to the stack (that would break all programs that don't specifically handle this case), and we only have two bits in the beam return value for extra data (at least one of which will be used for friend/foe marking).

**Comment by kirtangajjar** [comment]
Nope, Actually I was disconnected from the development of project and thought the beam sensor could not detect gold/battery lying in the open. Sorry for the misunderstanding.

**Comment by krisives** [comment]
@kirtangajjar Anyone is always welcome to post a question on Github issues and we will answer it.

**Comment by MLanghof** [comment]
Fixed by #192.
