### ISSUE TITLE
Gold/battery size is... pointless?

### ISSUE THREAD

**Issue by MLanghof** [asmcup/runtime#133]
I don't see the point in having different sizes for battery/gold items. I think they will be collected regardless of size, meaning there's no decision (and no "gameplay depth") associated with them. Rather, they "fuzz" the score of the bots.

Given the issue in #132, removing the size would also help in the future.

I won't go so far as to suggest uniting both gold and battery into a single item (because, again, I don't think bots will ever turn down either), but I don't see which benefit the variable size brings.

**Comment by MLanghof** [comment]
...any objections to making the item values constant? I mean, the GA already acts like they are, precisely because for the reasons detailed in this issue...

**Comment by krisives** [comment]
I think it's a good idea there is no reason to have gold/battery variation as it would add gambling aspects of the game / lower the skill ceiling.
