### ISSUE TITLE
popf branches instead of popping

### ISSUE THREAD

**Issue by MLanghof** [asmcup/runtime#14]
https://github.com/asmcup/runtime/blob/1.0.5-Alpha/src/asmcup/compiler/Compiler.java#L275

I'm really not experienced with assembler as of now, but that looks very wrong to me.

And to keep going with the confusion, I'm 99% sure that [this](https://github.com/asmcup/runtime/blob/1.0.5-Alpha/src/asmcup/vm/VM.java#L404) function should have reads in the first 2 cases. Otherwise the code emitted by the compiler makes no sense.

**Comment by krisives** [comment]
Great find and fixes. Thank you!
