### ISSUE TITLE
missing fetch/peek instruction

### ISSUE THREAD

**Issue by mrexodia** [asmcup/runtime#150]
Hello,

I have been looking at the various instructions but there seems to be no way to access data relative to the stack pointer (or the stack pointer itself for that matter). More specifically I would like to have a command `fetch n` that pushes the n-th value down the stack on top of the stack (`dup` could then be implemented as `fetch 0`).

My main motivation is that I'm looking into creating an LLVM backend for this machine and the `fetch` instruction is essential. An interesting paper is available [here](http://elc.yonsei.ac.kr/publications/treegraphs.pdf) and slides [here](http://elc.yonsei.ac.kr/publications/TreegraphbIS-bytecode11.pdf).

In my opinion it could be best implemented by adding an additional argument to the `dup` instructions and let `dup` default to `dup 0` for backwards compatibility.

Edit this seems related to #93

**Comment by MLanghof** [comment]
`dup` is a function, therefore it already uses all 8 bits of the instruction. The offset therefore needs to be an extra data byte (and `fetch` has to be a new instruction).

I still agree that this would be a useful thing to have (although my use cases for it so far were limited to those where a simple `pop8` accomplished the same), I'm not sure what @krisives thinks about changing the API/ABI at this stage?

**Comment by krisives** [comment]
Looking into this some more, sorry for the delay. Trying to come up with a potential solution for LLVM based compilers.
