### ISSUE TITLE
Bots can't distinguish walls and obstacles

### ISSUE THREAD

**Issue by MLanghof** [asmcup/runtime#154]
It's currently virtually impossible for a robot to (purposely) destroy a room entrance blockage, because it is indistinguishable from the surrounding wall tiles.

The beam currently only has a flag for "solid".

It's also worth mentioning that the unused bits (well, 2 of them) will eventually be used to house "variation" data.

**Comment by krisives** [comment]
Need to add:
- SENSOR_OBSTACLE = 16
- SENSOR_ROBOT = 32

Then implement the remaining 2 bits for denoting variation.
