### ISSUE TITLE
Line end failure in decompiler test

### ISSUE THREAD

**Issue by MLanghof** [asmcup/runtime#157]
```
decompiler.dump(0xff, "blabla");
assertEquals("ff: blabla\n", out.toString("UTF-8"));
```
This test fails for me locally. Using the following string instead, it succeeds: ff: "blabla\r\n".

The same failure happens in the other decompiler test. Yay for age-old line end incompatibilities.

**Comment by SiebelsTim** [comment]
Haha yey. I think I broke this in the static analysis diff.
It's an easy fix though
