### ISSUE TITLE
Are you still alive?

### ISSUE THREAD

**Issue by MLanghof** [asmcup/runtime#204]
I couldn't reach you over Skype in 2 months. Which always-on VM is that always-"away" account running on? :D

**Comment by krisives** [comment]
Hamburgers.

**Comment by krisives** [comment]
I still have plans to fix ASMCup and relaunch without any promises for prizes. The negotiations with sponsors took a long time and fell through so I will be giving up on those and will run the event as purely an open source bragging rights thing sponsors can suck it.
