### ISSUE TITLE
Output compiler errors

### ISSUE THREAD

**Issue by MLanghof** [asmcup/runtime#26]
Right now there are plenty of exceptions thrown by the compiler, we would just need to trace them back to the line (and column?) they're from and dump them into a message box to actually give the users the feedback.

**Comment by kirtangajjar** [comment]
I was thinking of doing it if #28 get resolved

**Comment by krisives** [comment]
I suggest the simplest way to do this is to add a member variable called `lineNumber` to `Compiler` and to have the `compile()` methods keep track of the line number. Then when the exception is caught use `compiler.getLineNumber()` or similar to know which line failed? Just my two cents.

**Comment by MLanghof** [comment]
Yes Kris, that was what I was thinking of, too.
