### ISSUE TITLE
Add steps to build from source

### ISSUE THREAD

**Issue by kirtangajjar** [asmcup/runtime#28]
I would like to contribute small changes to this project, but I was unable to do so as I was not able to build the project. 

I am familiar enough with java to make changes to code, but am unfamiliar with build.jardesc file(looks like an eclipse file). It would be great to have steps in readme detailing how to compile the project.

**Comment by krisives** [comment]
I will get a .project file added so you can import easier within Eclipse and probably add an ANT script so that you can use `ant` to build outside of Eclipse.

**Comment by krisives** [comment]
You can now build with ant or import into Eclipse. Let me know if this works for you.

**Comment by kirtangajjar** [comment]
I tried doing it with both ant and eclipse, and i'm getting same error in both

`Could not find or load main class src.asmcup.compiler.Main`

**Comment by kirtangajjar** [comment]
Try the following steps - 

```
git clone https://github.com/asmcup/runtime`
cd runtime
ant
cd lib
./asmcup.jar
```

**Comment by SiebelsTim** [comment]
running `ant` creates the .jar file without any classes in it. 

@kirtangajjar Additionally, eclipse thinks `src/` is the start of a package.

@krisives I'd be great to have a gradle script, as gradle can be imported in many different IDEs now.
I might do something later this day for this.

**Comment by krisives** [comment]
Building on a Linux server to make sure it's all easy to do w/out any big toolchains. Should see some fixes come soon.
