### ISSUE TITLE
Wiki

### ISSUE THREAD

**Issue by MLanghof** [asmcup/runtime#31]
The readme is getting really long and burdened with information. I feel like a/the wiki would be a perfect place to collect and group that info.

Any ideas/comments on basic structure/setup and what should be prioritized?

**Comment by kirtangajjar** [comment]
Exactly, that's what I was thinking about.

The best way to structure README would be -

**Introduction** 

We already have this, but it would be better to elaborate it a bit about `asmcup`. i.e. 
- Who is sponsoring it
- What will the task be like
- What will be the prizes (arbitrary points on leaderboard is my best guess but I may be wrong). 

**Screenshot**

We have it and current one's good enough

**Getting Started**

Should contain 
- where to find current jar 
- how to run it
- A small code snippet for some basic task like moving the morter, reading input from beam etc...
- Link to wiki where rest of the stuff is

**Building**

 Should contain the steps to build from source i.e 
- `git clone blah`
- `cd blah`
- `ant`
- `./myjar`

also specify dependencies (if any) like java(obvious) and if any specific version is insisted, jolt it down here. 

**Contributing**

This one is optional. It should contain a link to CONTRIBUTING.md which will have coding guidelines, naming convention etc... but doing it is boring and pointless for a small project so it's cool if it is skipped.

**Comment by krisives** [comment]
Yeah we need to simplify the README and use a Wiki for the more in-depth stuff. If someone else can do this  I would be grateful.

**Comment by MLanghof** [comment]
We can't open the wiki ourselves if I'm not mistaken. Clicking the wiki tab just sends you to the front page.

**Comment by krisives** [comment]
It's open now I will restrict access if needed.

**Comment by krisives** [comment]
Check out the Wiki and help if anyone wants to. I simplified the README so that it's basic and moved the specification details into SPEC.md so they can continue to be part of the main repository and be tracked with changes we make.

The Wiki serves to document things for users and provide a more complete view of the project and where to find more specific details.
