### ISSUE TITLE
Unit tests

### ISSUE THREAD

**Issue by MLanghof** [asmcup/runtime#41]
We've postponed them for a while now, but it's clearly essential to have a unit testing framework for something as complex as a compiler+decompiler and a VM.

I have very little experience with java toolchains/workflows/IDEs atm, so if somebody could set it up (and maybe an example), that would save a lot of time.

**Comment by krisives** [comment]
I have experience setting up JUnit, but last time I did it I had to add a junit.jar to the project and I want to avoid doing that here. I was planning on using TravisCI to automatically run the tests. Anyone want to help?

**Comment by SiebelsTim** [comment]
You'd still need junit for Travis. However gradle could download it, so that you don't have to check it into git

**Comment by krisives** [comment]
@SiebelsTim Yes I still want to use JUnit but I want to avoid storing the .jar inside of our repo. However that is possible with TravisCI or involves gradle I'm not worried how it's done too much.

**Comment by SiebelsTim** [comment]
I think I'll do something tomorrow :)

**Comment by krisives** [comment]
I removed "openjdk8" from the .travis.yml file since apparently it can't find it on Travis CI.

**Comment by SiebelsTim** [comment]
That's weird. Especially since it worked for my fork. Nothing I would care much about though. Thanks. 

Edit:
Oops, scratch that. It didn't. Openjdk stops at 7 on Travis

**Comment by krisives** [comment]
Thanks again to @SiebelsTim for adding the build and unit test framework. I'm gonna close this issue, but if we need a unit test added we should open a new issue and add the `help wanted` label or simply code it themselves and make a PR.

Cheers!
