### ISSUE TITLE
Negative speed is unlimited

### ISSUE THREAD

**Issue by MLanghof** [asmcup/runtime#6]
Just adapting the sample code:

```
start:

pushf -1.0
push8 #IO_MOTOR
io

jmp start
```

[Only positive max speed is enforced](https://github.com/asmcup/runtime/blob/master/src/asmcup/runtime/Robot.java#L103). Don't know if the lower bound should be -MAX_SPEED or 0.

**Comment by krisives** [comment]
Thank you for reporting this it will be fixed shortly.

**EDIT** Also with regards to if it should be -MAX_SPEED or 0, it will be a new constant I will call MIN_SPEED and equal to MAX_SPEED \* -0.5
