### ISSUE TITLE
Improve name of a variable

### ISSUE THREAD

**Issue by kirtangajjar** [asmcup/runtime#60]
Requesting anyone familiar with source to change the variable name of ["pc"](https://github.com/asmcup/runtime/blob/master/src/asmcup/compiler/Compiler.java#L11) to a more descriptive one. 

I was going through code and have no idea what it is

**Comment by krisives** [comment]
PC stands for "program counter" and is pretty common in CPU specs.

**Comment by kirtangajjar** [comment]
Oh, cool!

**Comment by krisives** [comment]
I would say the terminology used in a lot of the code is a mixture of Java (like how the stack works similarly to Java byte code) and 6502 (like how the program counter is called PC and the stack pointer SP) That might help anyone less familiar with some of the terms.
