### ISSUE TITLE
Copy ROM doesn't work as expected

### ISSUE THREAD

**Issue by MLanghof** [asmcup/runtime#70]
https://github.com/asmcup/runtime/blob/master/src/asmcup/sandbox/Genetics.java#L175

`rom` is only ever changed by the `loadROM()` method below it. So `getROM()` will only return the ROM that was last loaded, with no relation to what the bot currently has.

**Comment by krisives** [comment]
Doesn't Genetics do `sandbox.loadROM(getBest().ram.clone());` which should set the ROM?

**Comment by MLanghof** [comment]
Oh, I may have missed that. Sorry!

**Comment by MLanghof** [comment]
Ok I looked into this again, and the raising of this issue resulted from the fact that you can't type code in the editor, compile&flash it and then Copy ROM it. You are right that Genetics changes the ROM stored in the Sandbox - Compile&Flash doesn't though. This is pretty unintuitive behavior for a button in the sandbox menu (as opposed to, say, the genetics menu).

**Comment by krisives** [comment]
Fixed by #76 

If anyone notices copy and paste not working please re-open this!
