### ISSUE TITLE
Code editor enhancements

### ISSUE THREAD

**Issue by MLanghof** [asmcup/runtime#9]
- [x] The workflow would really benefit from shortcuts for at least Compile & Flash.
- [x] I have no idea what extension "source file" wants (well, I'd have to look into the code), it doesn't automatically append it to file names either. This means that trying to (re)open code files involves changing the filter to "all files" every time.
- [x] A "reload code" functionality might be really nice to have ("Open code" behaved this way in 1.0.3 iirc), allowing one to edit a code file in an external editor and then having a quick way to get the changes into the runtime.

**Comment by krisives** [comment]
>  The workflow would really benefit from shortcuts for at least Compile & Flash.

Obviously we can't pick the perfect hotkeys, but any ideas for shortcuts for this? I'll add support for CTRL+S and CTRL+O to map to save/open to start.

>  I have no idea what extension "source file" wants (well, I'd have to look into the code), it doesn't automatically append it to file names either. This means that trying to (re)open code files involves changing the filter to "all files" every time.

Good catch this needs to be fixed. It's looking for *.asm files.

>  A "reload code" functionality might be really nice to have ("Open code" behaved this way in 1.0.3 iirc), allowing one to edit a code file in an external editor and then having a quick way to get the changes into the runtime.

I'll add a File => Reload option.

Thanks again for the feedback and help.

**Comment by MLanghof** [comment]
I'll go on a tangent here and ask if your foresee a necessity for having distinct syntax check and compilation. I can (kind of) see the purpose of separating compiling from flashing, but wouldn't "compile" by itself be enough to satisfy the "I'm not sure if my code will work, tell me" side?
