### ISSUE TITLE
IO_COMPASS Issue

### ISSUE THREAD

**Issue by enusbaum** [asmcup/runtime#90]
It appears the value of IO_COMPASS will only increment while turning clockwise and decrement while turning counter clockwise.

With the following code, you can observe the value increasing on the stack over time.

```
pushf 0.2
push8 #IO_STEER
io
loop:
push8 #IO_COMPASS
io
popf $FF
jmp loop
```

My understanding is that if I rotate the bot 360 degrees, IO_COMPASS should return the same value. In this case, because it keeps de/incrementing depending on the direction, the values will never be the same for the same given point.

**Comment by krisives** [comment]
You are correct I will fix this to return the expected range of -PI to +PI
