### ISSUE TITLE
push8r, pop8r, jnzr

### ISSUE THREAD

**Issue by MLanghof** [asmcup/runtime#96]
I've talked about this with @krisives before, but I figured hearing a few more voices would help.

These relative commands make use of the 6 data bits each instruction can have. Consequently, they take only one byte, but they are only legal if your target address is within 63 bytes of the instruction you're executing. To be sure of this when you write the code, you sort of need to know the compiled code beforehand though.

Kris' envisioned use for these commands is loops and "registers"/variables close to the point of execution. I can see the point for loops/jumps, but I don't think spreading your registers throughout your code is particularly desirable.
I'd suggest that push8r and pop8r instead interpret the 6 data bits as actual address (and not as offset). This would mean that "registers" within the first ~60 bytes of the code would only take 1 byte of instructions to read from/write to. A disadvantage would be that programmers probably have to jump past their registers into their actual code at program start though.

Thoughts?

(Writing this, I noticed that all these commands also only take labels - actual memory addresses aren't allowed. Doesn't seem particularly important, but the compiler should probably give a better error for it (currently "null").)

**Comment by krisives** [comment]
> Kris' envisioned use for these commands is loops and "registers"/variables close to the point of execution. I can see the point for loops/jumps, but I don't think spreading your registers throughout your code is particularly desirable.

Mainly for conditional branches / loops and if you want your bot to have subroutines w/ locals. I view this as a trade-off it will make loops and conditional branches take two bytes.

**Comment by MLanghof** [comment]
Well `jnzr` can work differently from `push8r` and `pop8r`, no? Maybe the latter would be renamed to avoid confusion.

**Comment by krisives** [comment]
I think it's too late to change the core VM spec this much right now. 

I do have a path to allow robots to use different VM instruction languages, the first implementation we are using now will probably be called "VM1" or similar and our next iteration will be called "VM2" etc. giving us a clean pathway to allow old bots and new bots to run in the same game world and give coders the ability to pick which instruction language fits their needs and style.
